# generated by datamodel-codegen:
#   filename:  https://json.schemastore.org/traefik-v2-file-provider.json
#   timestamp: 2022-04-23T08:32:35+00:00
# ruff: noqa

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field, confloat, conint


class Certificate(BaseModel):
    certFile: Optional[str] = None
    keyFile: Optional[str] = None
    stores: Optional[List[str]] = Field(
        None,
        description='A list of stores can be specified here to indicate where the certificates should be stored. Although the stores list will actually be ignored and automatically set to ["default"].',
    )


class ClientAuth(BaseModel):
    caFiles: Optional[List[str]] = Field(
        None,
        description="For authentication policies that require verification of the client certificate, the certificate authority for the certificate should be set here.",
    )
    clientAuthType: Optional[str] = None


class Options(BaseModel):
    minVersion: Optional[str] = Field(None, description="Minimum TLS Version")
    maxVersion: Optional[str] = Field(
        None,
        description="Maximum TLS Version. It is discouraged to use of this setting to disable TLS1.3. The recommended approach is to update the clients to support TLS1.3.",
    )
    cipherSuites: Optional[List[str]] = Field(
        None,
        description="Cipher suites defined for TLS 1.2 and below cannot be used in TLS 1.3, and vice versa. With TLS 1.3, the cipher suites are not configurable (all supported cipher suites are safe in this case).",
    )
    curvePreferences: Optional[List[str]] = Field(
        None,
        description="This option allows to set the preferred elliptic curves in a specific order.\n\nThe names of the curves defined by crypto (e.g. CurveP521) and the RFC defined names (e.g. secp521r1) can be used.",
    )
    sniStrict: Optional[bool] = Field(
        None,
        description="With strict SNI checking enabled, Traefik won't allow connections from clients that do not specify a server_name extension or don't match any certificate configured on the tlsOption.",
    )
    preferServerCipherSuites: Optional[bool] = Field(
        None,
        description="This option allows the server to choose its most preferred cipher suite instead of the client's. Please note that this is enabled automatically when minVersion or maxVersion are set.",
    )
    clientAuth: Optional[ClientAuth] = Field(
        None,
        description="Traefik supports mutual authentication, through the clientAuth section.",
    )


class DefaultCertificate(BaseModel):
    certFile: Optional[str] = None
    keyFile: Optional[str] = None


class Stores(BaseModel):
    defaultCertificate: Optional[DefaultCertificate] = Field(
        None,
        description="Traefik can use a default certificate for connections without a SNI, or without a matching domain. If no default certificate is provided, Traefik generates and uses a self-signed certificate.",
    )


class Tls(BaseModel):
    certificates: Optional[List[Certificate]] = None
    options: Optional[Dict[str, Options]] = Field(
        None,
        description="The TLS options allow one to configure some parameters of the TLS connection.",
    )
    stores: Optional[Dict[str, Stores]] = Field(
        None,
        description="Any store definition other than the default one (named default) will be ignored, and there is therefore only one globally available TLS store.",
    )


class Domain(BaseModel):
    main: Optional[str] = None
    sans: Optional[List[str]] = None


class Tls1(BaseModel):
    options: Optional[str] = Field(
        None,
        description="The options field enables fine-grained control of the TLS parameters. It refers to a TLS Options and will be applied only if a Host rule is defined.",
    )
    certResolver: Optional[str] = Field(
        None,
        description="If certResolver is defined, Traefik will try to generate certificates based on routers Host & HostSNI rules.",
    )
    domains: Optional[List[Domain]] = Field(
        None,
        description="You can set SANs (alternative domains) for each main domain. Every domain must have A/AAAA records pointing to Traefik. Each domain & SAN will lead to a certificate request.",
    )


class HttpRouter(BaseModel):
    entryPoints: Optional[List[str]] = Field(
        None,
        description="If not specified, HTTP routers will accept requests from all defined entry points. If you want to limit the router scope to a set of entry points, set the entryPoints option.",
    )
    rule: str = Field(
        ...,
        description="Rules are a set of matchers configured with values, that determine if a particular request matches specific criteria. If the rule is verified, the router becomes active, calls middlewares, and then forwards the request to the service.",
    )
    priority: Optional[conint(ge=0)] = Field(
        0,
        description="To avoid path overlap, routes are sorted, by default, in descending order using rules length. The priority is directly equal to the length of the rule, and so the longest length has the highest priority. A value of 0 for the priority is ignored: priority = 0 means that the default rules length sorting is used.",
    )
    middlewares: Optional[List[str]] = Field(
        None,
        description="You can attach a list of middlewares to each HTTP router. The middlewares will take effect only if the rule matches, and before forwarding the request to the service. Middlewares are applied in the same order as their declaration in router.",
    )
    service: str = Field(
        ...,
        description="Each request must eventually be handled by a service, which is why each router definition should include a service target, which is basically where the request will be passed along to. HTTP routers can only target HTTP services (not TCP services).",
    )
    tls: Optional[Tls1] = Field(
        None,
        description="When a TLS section is specified, it instructs Traefik that the current router is dedicated to HTTPS requests only (and that the router should ignore HTTP (non TLS) requests). Traefik will terminate the SSL connections (meaning that it will send decrypted data to the services). If you need to define the same route for both HTTP and HTTPS requests, you will need to define two different routers: one with the tls section, one without.",
    )


class Server(BaseModel):
    url: str = Field(
        ...,
        description="The url option point to a specific instance. Paths in the servers' url have no effect. If you want the requests to be sent to a specific path on your servers, configure your routers to use a corresponding middleware (e.g. the AddPrefix or ReplacePath) middlewares.",
    )


class Cookie(BaseModel):
    name: Optional[str] = Field(
        None,
        description="The default cookie name is an abbreviation of a sha1 (ex: _1d52e).",
    )
    secure: Optional[bool] = False
    httpOnly: Optional[bool] = False
    sameSite: Optional[str] = Field(
        "", description="Can be none, lax, strict or empty."
    )


class Sticky(BaseModel):
    cookie: Optional[Cookie] = None


class HealthCheck(BaseModel):
    path: Optional[str] = Field(
        None,
        description="path is appended to the server URL to set the health check endpoint.",
    )
    scheme: Optional[str] = Field(
        None,
        description="If defined, will replace the server URL scheme for the health check endpoint",
    )
    hostname: Optional[str] = Field(
        None,
        description="If defined, will apply Host header hostname to the health check request.",
    )
    port: Optional[int] = Field(
        None,
        description="If defined, will replace the server URL port for the health check endpoint.",
    )
    interval: Optional[str] = Field(
        None,
        description="Defines the frequency of the health check calls. Interval is to be given in a format understood by `time.ParseDuration`. The interval must be greater than the timeout. If configuration doesn't reflect this, the interval will be set to timeout + 1 second.",
    )
    timeout: Optional[str] = Field(
        None,
        description="Defines the maximum duration Traefik will wait for a health check request before considering the server failed (unhealthy). Timeout is to be given in a format understood by `time.ParseDuration`.",
    )
    headers: Optional[Dict[str, str]] = Field(
        None,
        description="Defines custom headers to be sent to the health check endpoint.",
    )
    followRedirects: Optional[bool] = Field(
        True,
        description="Defines whether redirects should be followed during the health check calls (default: true).",
    )


class ResponseForwarding(BaseModel):
    flushInterval: Optional[str] = Field(
        None,
        description="Specifies the interval in between flushes to the client while copying the response body. It is a duration in milliseconds, defaulting to 100. A negative value means to flush immediately after each write to the client. The flushInterval is ignored when ReverseProxy recognizes a response as a streaming response; for such responses, writes are flushed to the client immediately.",
    )


class HttpLoadBalancerService(BaseModel):
    servers: List[Server] = Field(
        ...,
        description="Servers declare a single instance of your program.",
        min_items=1,
    )
    sticky: Optional[Sticky] = Field(
        None,
        description="When sticky sessions are enabled, a cookie is set on the initial request and response to let the client know which server handles the first response. On subsequent requests, to keep the session alive with the same server, the client should resend the same cookie.",
    )
    healthCheck: Optional[HealthCheck] = Field(
        None,
        description="Configure health check to remove unhealthy servers from the load balancing rotation. Traefik will consider your servers healthy as long as they return status codes between 2XX and 3XX to the health check requests (carried out every interval). Traefik keeps monitoring the health of unhealthy servers. If a server has recovered (returning 2xx -> 3xx responses again), it will be added back to the load balancer rotation pool.",
    )
    passHostHeader: Optional[bool] = Field(
        True,
        description="The passHostHeader allows to forward client Host header to server. By default, passHostHeader is true.",
    )
    responseForwarding: Optional[ResponseForwarding] = Field(
        None,
        description="Defines how Traefik forwards the response from the backend server to the client.",
    )


class Service(BaseModel):
    name: Optional[str] = None
    weight: Optional[float] = None


class HttpWeightedService(BaseModel):
    services: Optional[List[Service]] = None


class Mirror(BaseModel):
    name: Optional[str] = None
    percent: Optional[confloat(ge=0.0, le=100.0)] = None


class HttpMirroringService(BaseModel):
    service: Optional[str] = None
    maxBodySize: Optional[int] = Field(
        -1,
        description="maxBodySize is the maximum size allowed for the body of the request. If the body is larger, the request is not mirrored. Default value is -1, which means unlimited size.",
    )
    mirrors: Optional[List[Mirror]] = None


class HttpServiceItem(BaseModel):
    class Config:
        extra = Extra.forbid

    loadBalancer: Optional[HttpLoadBalancerService] = None


class HttpServiceItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    weighted: Optional[HttpWeightedService] = None


class HttpServiceItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    mirroring: Optional[HttpMirroringService] = None


class HttpService(BaseModel):
    __root__: Union[HttpServiceItem, HttpServiceItem1, HttpServiceItem2] = Field(
        ...,
        description="The Services are responsible for configuring how to reach the actual services that will eventually handle the incoming requests.",
    )


class AddPrefixMiddleware(BaseModel):
    prefix: Optional[str] = Field(
        None,
        description="prefix is the string to add before the current path in the requested URL. It should include the leading slash (/).",
    )


class BasicAuthMiddleware(BaseModel):
    users: Optional[List[str]] = Field(
        None,
        description="The users option is an array of authorized users. Each user will be declared using the `name:hashed-password` format.",
    )
    usersFile: Optional[str] = Field(
        None,
        description="The usersFile option is the path to an external file that contains the authorized users for the middleware.\n\nThe file content is a list of `name:hashed-password`.",
    )
    realm: Optional[str] = Field(
        "traefik",
        description="You can customize the realm for the authentication with the realm option. The default value is traefik.",
    )
    headerField: Optional[str] = Field(
        None,
        description="You can define a header field to store the authenticated user using the headerField option.",
    )
    removeHeader: Optional[bool] = Field(
        False,
        description="Set the removeHeader option to true to remove the authorization header before forwarding the request to your service. (Default value is false.)",
    )


class BufferingMiddleware(BaseModel):
    maxRequestBodyBytes: Optional[int] = Field(
        None,
        description="With the maxRequestBodyBytes option, you can configure the maximum allowed body size for the request (in Bytes).\n\nIf the request exceeds the allowed size, it is not forwarded to the service and the client gets a 413 (Request Entity Too Large) response.",
    )
    memRequestBodyBytes: Optional[int] = Field(
        None,
        description="You can configure a threshold (in Bytes) from which the request will be buffered on disk instead of in memory with the memRequestBodyBytes option.",
    )
    maxResponseBodyBytes: Optional[int] = Field(
        None,
        description="With the maxResponseBodyBytes option, you can configure the maximum allowed response size from the service (in Bytes).\n\nIf the response exceeds the allowed size, it is not forwarded to the client. The client gets a 413 (Request Entity Too Large) response instead.",
    )
    memResponseBodyBytes: Optional[int] = Field(
        None,
        description="You can configure a threshold (in Bytes) from which the response will be buffered on disk instead of in memory with the memResponseBodyBytes option.",
    )
    retryExpression: Optional[str] = Field(
        None,
        description="You can have the Buffering middleware replay the request with the help of the retryExpression option.",
    )


class ChainMiddleware(BaseModel):
    middlewares: Optional[List[str]] = Field(None, min_items=1)


class CircuitBreakerMiddleware(BaseModel):
    expression: Optional[str] = Field(
        None,
        description="You can specify an expression that, once matched, will trigger the circuit breaker (and apply the fallback mechanism instead of calling your services).",
    )


class CompressMiddleware(BaseModel):
    excludedContentTypes: Optional[List[str]] = Field(
        None,
        description="excludedContentTypes specifies a list of content types to compare the Content-Type header of the incoming requests to before compressing.\n\nThe requests with content types defined in excludedContentTypes are not compressed.\n\nContent types are compared in a case-insensitive, whitespace-ignored manner.",
    )


class ContentTypeMiddleware(BaseModel):
    autoDetect: Optional[bool] = Field(
        False,
        description="autoDetect specifies whether to let the Content-Type header, if it has not been set by the backend, be automatically set to a value derived from the contents of the response.",
    )


class DigestAuthMiddleware(BaseModel):
    users: Optional[List[str]] = Field(
        None,
        description="The users option is an array of authorized users. Each user will be declared using the `name:realm:encoded-password` format.",
    )
    usersFile: Optional[str] = Field(
        None,
        description="The usersFile option is the path to an external file that contains the authorized users for the middleware.\n\nThe file content is a list of `name:realm:encoded-password`.",
    )
    realm: Optional[str] = Field(
        "traefik",
        description="You can customize the realm for the authentication with the realm option. The default value is traefik.",
    )
    headerField: Optional[str] = Field(
        None,
        description="You can customize the header field for the authenticated user using the headerField option.",
    )
    removeHeader: Optional[bool] = Field(
        False,
        description="Set the removeHeader option to true to remove the authorization header before forwarding the request to your service. (Default value is false.)",
    )


class ErrorsMiddleware(BaseModel):
    status: Optional[List[str]] = Field(
        None,
        description="The status that will trigger the error page.\n\nThe status code ranges are inclusive (500-599 will trigger with every code between 500 and 599, 500 and 599 included). You can define either a status code like 500 or ranges with a syntax like 500-599.",
    )
    service: Optional[str] = Field(
        None, description="The service that will serve the new requested error page."
    )
    query: Optional[str] = Field(
        None,
        description="The URL for the error page (hosted by service). You can use {status} in the query, that will be replaced by the received status code.",
    )


class Tls2(BaseModel):
    ca: Optional[str] = Field(
        None,
        description="Certificate Authority used for the secured connection to the authentication server.",
    )
    caOptional: Optional[bool] = Field(
        None,
        description="Policy used for the secured connection with TLS Client Authentication to the authentication server. Requires tls.ca to be defined.",
    )
    cert: Optional[str] = Field(
        None,
        description="Public certificate used for the secured connection to the authentication server.",
    )
    key: Optional[str] = Field(
        None,
        description="Private certificate used for the secure connection to the authentication server.",
    )
    insecureSkipVerify: Optional[bool] = Field(
        None,
        description="If insecureSkipVerify is true, TLS for the connection to authentication server accepts any certificate presented by the server and any host name in that certificate.",
    )


class ForwardAuthMiddleware(BaseModel):
    address: Optional[str] = Field(
        None,
        description="The address option defines the authentication server address.",
    )
    trustForwardHeader: Optional[bool] = Field(
        None,
        description="Set the trustForwardHeader option to true to trust all the existing X-Forwarded-* headers.",
    )
    authResponseHeaders: Optional[List[str]] = Field(
        None,
        description="The authResponseHeaders option is the list of the headers to copy from the authentication server to the request.",
    )
    authResponseHeadersRegex: Optional[str] = Field(
        None,
    )
    tls: Optional[Tls2] = Field(
        None,
        description="The tls option is the TLS configuration from Traefik to the authentication server.",
    )


class HeadersMiddleware(BaseModel):
    customRequestHeaders: Optional[Dict[str, str]] = Field(
        None,
        description="The customRequestHeaders option lists the Header names and values to apply to the request.",
    )
    customResponseHeaders: Optional[Dict[str, str]] = Field(
        None,
        description="The customResponseHeaders option lists the Header names and values to apply to the response.",
    )
    accessControlAllowCredentials: Optional[bool] = Field(
        None,
        description="The accessControlAllowCredentials indicates whether the request can include user credentials.",
    )
    accessControlAllowHeaders: Optional[List[str]] = Field(
        None,
        description="The accessControlAllowHeaders indicates which header field names can be used as part of the request.",
    )
    accessControlAllowMethods: Optional[List[str]] = Field(
        None,
        description="The accessControlAllowMethods indicates which methods can be used during requests.",
    )
    accessControlAllowOriginList: Optional[List[str]] = Field(
        None,
        description="The accessControlAllowOriginList indicates whether a resource can be shared by returning different values.\n\nA wildcard origin * can also be configured, and will match all requests. If this value is set by a backend server, it will be overwritten by Traefik\n\nThis value can contain a list of allowed origins.",
    )
    accessControlExposeHeaders: Optional[List[str]] = Field(
        None,
        description="The accessControlExposeHeaders indicates which headers are safe to expose to the api of a CORS API specification.",
    )
    accessControlMaxAge: Optional[int] = Field(
        None,
        description="The accessControlMaxAge indicates how long (in seconds) a preflight request can be cached.",
    )
    addVaryHeader: Optional[bool] = Field(
        None,
        description="The addVaryHeader is used in conjunction with accessControlAllowOriginList to determine whether the vary header should be added or modified to demonstrate that server responses can differ based on the value of the origin header.",
    )
    allowedHosts: Optional[List[str]] = Field(
        None,
        description="The allowedHosts option lists fully qualified domain names that are allowed.",
    )
    hostsProxyHeaders: Optional[List[str]] = Field(
        None,
        description="The hostsProxyHeaders option is a set of header keys that may hold a proxied hostname value for the request.",
    )
    sslRedirect: Optional[bool] = Field(
        None,
        description="The sslRedirect is set to true, then only allow https requests.",
    )
    sslTemporaryRedirect: Optional[bool] = Field(
        None,
        description="Set the sslTemporaryRedirect to true to force an SSL redirection using a 302 (instead of a 301).",
    )
    sslHost: Optional[str] = Field(
        None,
        description="The sslHost option is the host name that is used to redirect http requests to https.",
    )
    sslProxyHeaders: Optional[Dict[str, str]] = Field(
        None,
        description='The sslProxyHeaders option is set of header keys with associated values that would indicate a valid https request. Useful when using other proxies with header like: "X-Forwarded-Proto": "https".',
    )
    sslForceHost: Optional[bool] = Field(
        None,
        description="Set sslForceHost to true and set SSLHost to forced requests to use SSLHost even the ones that are already using SSL.",
    )
    stsSeconds: Optional[int] = Field(
        None,
        description="The stsSeconds is the max-age of the Strict-Transport-Security header. If set to 0, would NOT include the header.",
    )
    stsIncludeSubdomains: Optional[bool] = Field(
        None,
        description="The stsIncludeSubdomains is set to true, the includeSubDomains directive will be appended to the Strict-Transport-Security header.",
    )
    stsPreload: Optional[bool] = Field(
        None,
        description="Set stsPreload to true to have the preload flag appended to the Strict-Transport-Security header.",
    )
    forceSTSHeader: Optional[bool] = Field(
        None,
        description="Set forceSTSHeader to true, to add the STS header even when the connection is HTTP.",
    )
    frameDeny: Optional[bool] = Field(
        None,
        description="Set frameDeny to true to add the X-Frame-Options header with the value of DENY.",
    )
    customFrameOptionsValue: Optional[str] = Field(
        None,
        description="The customFrameOptionsValue allows the X-Frame-Options header value to be set with a custom value. This overrides the FrameDeny option.",
    )
    contentTypeNosniff: Optional[bool] = Field(
        None,
        description="Set contentTypeNosniff to true to add the X-Content-Type-Options header with the value nosniff.",
    )
    browserXssFilter: Optional[bool] = Field(
        None,
        description="Set browserXssFilter to true to add the X-XSS-Protection header with the value 1; mode=block.",
    )
    customBrowserXSSValue: Optional[str] = Field(
        None,
        description="The customBrowserXssValue option allows the X-XSS-Protection header value to be set with a custom value. This overrides the BrowserXssFilter option.",
    )
    contentSecurityPolicy: Optional[str] = Field(
        None,
        description="The contentSecurityPolicy option allows the Content-Security-Policy header value to be set with a custom value.",
    )
    publicKey: Optional[str] = Field(
        None,
        description="The publicKey implements HPKP to prevent MITM attacks with forged certificates.",
    )
    referrerPolicy: Optional[str] = Field(
        None,
        description="The referrerPolicy allows sites to control when browsers will pass the Referer header to other sites.",
    )
    featurePolicy: Optional[str] = Field(
        None, description="The featurePolicy allows sites to control browser features."
    )
    isDevelopment: Optional[bool] = Field(
        None,
        description="Set isDevelopment to true when developing. The AllowedHosts, SSL, and STS options can cause some unwanted effects. Usually testing happens on http, not https, and on localhost, not your production domain.\nIf you would like your development environment to mimic production with complete Host blocking, SSL redirects, and STS headers, leave this as false.",
    )


class IpStrategy(BaseModel):
    depth: Optional[int] = Field(
        None,
        description="The depth option tells Traefik to use the X-Forwarded-For header and take the IP located at the depth position (starting from the right). If depth is greater than the total number of IPs in X-Forwarded-For, then the client IP will be empty. depth is ignored if its value is lesser than or equal to 0.",
    )
    excludedIPs: Optional[List[str]] = Field(
        None,
        description="excludedIPs tells Traefik to scan the X-Forwarded-For header and pick the first IP not in the list. If depth is specified, excludedIPs is ignored.",
    )


class IpWhiteListMiddleware(BaseModel):
    sourceRange: Optional[List[str]] = Field(
        None,
        description="The sourceRange option sets the allowed IPs (or ranges of allowed IPs by using CIDR notation).",
    )
    ipStrategy: Optional[IpStrategy] = None


class SourceCriterion(BaseModel):
    ipStrategy: Optional[IpStrategy] = None
    requestHeaderName: Optional[str] = Field(
        None,
        description="Requests having the same value for the given header are grouped as coming from the same source.",
    )
    requestHost: Optional[bool] = Field(
        None, description="Whether to consider the request host as the source."
    )


class InFlightReqMiddleware(BaseModel):
    amount: Optional[int] = Field(
        None,
        description="The amount option defines the maximum amount of allowed simultaneous in-flight request. The middleware will return an HTTP 429 Too Many Requests if there are already amount requests in progress (based on the same sourceCriterion strategy).",
    )
    sourceCriterion: Optional[SourceCriterion] = None


class Subject(BaseModel):
    country: Optional[bool] = Field(
        None,
        description="Set the country option to true to add the country information into the subject.",
    )
    province: Optional[bool] = Field(
        None,
        description="Set the province option to true to add the province information into the subject.",
    )
    locality: Optional[bool] = Field(
        None,
        description="Set the locality option to true to add the locality information into the subject.",
    )
    organization: Optional[bool] = Field(
        None,
        description="Set the organization option to true to add the organization information into the subject.",
    )
    commonName: Optional[bool] = Field(
        None,
        description="Set the commonName option to true to add the commonName information into the subject.",
    )
    serialNumber: Optional[bool] = Field(
        None,
        description="Set the serialNumber option to true to add the serialNumber information into the subject.",
    )
    domainComponent: Optional[bool] = Field(
        None,
        description="Set the domainComponent option to true to add the domainComponent information into the subject.",
    )


class Issuer(BaseModel):
    country: Optional[bool] = Field(
        None,
        description="Set the country option to true to add the country information into the issuer.",
    )
    province: Optional[bool] = Field(
        None,
        description="Set the province option to true to add the province information into the issuer.",
    )
    locality: Optional[bool] = Field(
        None,
        description="Set the locality option to true to add the locality information into the issuer.",
    )
    organization: Optional[bool] = Field(
        None,
        description="Set the organization option to true to add the organization information into the issuer.",
    )
    commonName: Optional[bool] = Field(
        None,
        description="Set the commonName option to true to add the commonName information into the issuer.",
    )
    serialNumber: Optional[bool] = Field(
        None,
        description="Set the serialNumber option to true to add the serialNumber information into the issuer.",
    )
    domainComponent: Optional[bool] = Field(
        None,
        description="Set the domainComponent option to true to add the domainComponent information into the issuer.",
    )


class Info(BaseModel):
    notAfter: Optional[bool] = Field(
        None,
        description="Set the notAfter option to true to add the Not After information from the Validity part.",
    )
    notBefore: Optional[bool] = Field(
        None,
        description="Set the notBefore option to true to add the Not Before information from the Validity part.",
    )
    sans: Optional[bool] = Field(
        None,
        description="Set the sans option to true to add the Subject Alternative Name information from the Subject Alternative Name part.",
    )
    subject: Optional[Subject] = Field(
        None,
        description="The subject select the specific client certificate subject details you want to add to the X-Forwarded-Tls-Client-Cert-Info header.",
    )
    issuer: Optional[Issuer] = Field(
        None,
        description="The issuer select the specific client certificate issuer details you want to add to the X-Forwarded-Tls-Client-Cert-Info header.",
    )


class PassTLSClientCertMiddleware(BaseModel):
    pem: Optional[bool] = Field(
        None,
        description="The pem option sets the X-Forwarded-Tls-Client-Cert header with the escape certificate.",
    )
    info: Optional[Info] = Field(
        None,
        description="The info option select the specific client certificate details you want to add to the X-Forwarded-Tls-Client-Cert-Info header. The value of the header will be an escaped concatenation of all the selected certificate details.",
    )


class PluginMiddleware(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class RateLimitMiddleware(BaseModel):
    average: Optional[float] = Field(
        0,
        description="average is the maximum rate, by default in requests by second, allowed for the given source.\n\nIt defaults to 0, which means no rate limiting.\n\nThe rate is actually defined by dividing average by period. So for a rate below 1 req/s, one needs to define a period larger than a second.",
    )
    period: Optional[float] = Field(
        1,
        description="period, in combination with average, defines the actual maximum rate.\n\nIt defaults to 1 second.",
    )
    burst: Optional[float] = Field(
        1,
        description="burst is the maximum number of requests allowed to go through in the same arbitrarily small period of time.\n\nIt defaults to 1.",
    )
    sourceCriterion: Optional[SourceCriterion] = None


class RedirectRegexMiddleware(BaseModel):
    permanent: Optional[bool] = Field(
        None,
        description="Set the permanent option to true to apply a permanent redirection.",
    )
    regex: Optional[str] = Field(
        None,
        description="The regex option is the regular expression to match and capture elements from the request URL.",
    )
    replacement: Optional[str] = Field(
        None,
        description="The replacement option defines how to modify the URL to have the new target URL. Care should be taken when defining replacement expand variables: $1x is equivalent to ${1x}, not ${1}x (see Regexp.Expand), so use ${1} syntax.",
    )


class RedirectSchemeMiddleware(BaseModel):
    permanent: Optional[bool] = Field(
        None,
        description="Set the permanent option to true to apply a permanent redirection.",
    )
    scheme: Optional[str] = Field(
        None, description="The scheme option defines the scheme of the new url."
    )
    port: Optional[str] = Field(
        None,
        description="The port option defines the port of the new url. Port in this configuration is a string, not a numeric value.",
    )


class ReplacePathMiddleware(BaseModel):
    path: Optional[str] = Field(
        None,
        description="The path option defines the path to use as replacement in the request url.",
    )


class ReplacePathRegexMiddleware(BaseModel):
    regex: Optional[str] = Field(
        None,
        description="The regex option is the regular expression to match and capture the path from the request URL.",
    )
    replacement: Optional[str] = Field(
        None,
        description="The replacement option defines how to modify the path to have the new target path. Care should be taken when defining replacement expand variables: $1x is equivalent to ${1x}, not ${1}x (see Regexp.Expand), so use ${1} syntax.",
    )


class RetryMiddleware(BaseModel):
    attempts: int = Field(
        ...,
        description="The attempts option defines how many times the request should be retried.",
    )


class StripPrefixMiddleware(BaseModel):
    prefixes: Optional[List[str]] = Field(
        None,
        description="The prefixes option defines the prefixes to strip from the request URL",
    )
    forceSlash: Optional[bool] = Field(
        None,
        description="The forceSlash option makes sure that the resulting stripped path is not the empty string, by replacing it with / when necessary.\n\nThis option was added to keep the initial (non-intuitive) behavior of this middleware, in order to avoid introducing a breaking change.\n\nIt's recommended to explicitly set forceSlash to false.",
    )


class StripPrefixRegexMiddleware(BaseModel):
    regex: Optional[List[str]] = Field(
        None,
        description="The regex option is the regular expression to match the path prefix from the request URL.",
    )


class HttpMiddlewareItem(BaseModel):
    class Config:
        extra = Extra.forbid

    addPrefix: Optional[AddPrefixMiddleware] = None


class HttpMiddlewareItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    basicAuth: Optional[BasicAuthMiddleware] = None


class HttpMiddlewareItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    buffering: Optional[BufferingMiddleware] = None


class HttpMiddlewareItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    chain: Optional[ChainMiddleware] = None


class HttpMiddlewareItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    circuitBreaker: Optional[CircuitBreakerMiddleware] = None


class HttpMiddlewareItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    compress: Optional[CompressMiddleware] = None


class HttpMiddlewareItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    contentType: Optional[ContentTypeMiddleware] = None


class HttpMiddlewareItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    digestAuth: Optional[DigestAuthMiddleware] = None


class HttpMiddlewareItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    errors: Optional[ErrorsMiddleware] = None


class HttpMiddlewareItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    forwardAuth: Optional[ForwardAuthMiddleware] = None


class HttpMiddlewareItem10(BaseModel):
    class Config:
        extra = Extra.forbid

    headers: Optional[HeadersMiddleware] = None


class HttpMiddlewareItem11(BaseModel):
    class Config:
        extra = Extra.forbid

    ipWhiteList: Optional[IpWhiteListMiddleware] = None


class HttpMiddlewareItem12(BaseModel):
    class Config:
        extra = Extra.forbid

    inFlightReq: Optional[InFlightReqMiddleware] = None


class HttpMiddlewareItem13(BaseModel):
    class Config:
        extra = Extra.forbid

    passTLSClientCert: Optional[PassTLSClientCertMiddleware] = None


class HttpMiddlewareItem14(BaseModel):
    class Config:
        extra = Extra.forbid

    plugin: Optional[PluginMiddleware] = None


class HttpMiddlewareItem15(BaseModel):
    class Config:
        extra = Extra.forbid

    rateLimit: Optional[RateLimitMiddleware] = None


class HttpMiddlewareItem16(BaseModel):
    class Config:
        extra = Extra.forbid

    redirectRegex: Optional[RedirectRegexMiddleware] = None


class HttpMiddlewareItem17(BaseModel):
    class Config:
        extra = Extra.forbid

    redirectScheme: Optional[RedirectSchemeMiddleware] = None


class HttpMiddlewareItem18(BaseModel):
    class Config:
        extra = Extra.forbid

    replacePath: Optional[ReplacePathMiddleware] = None


class HttpMiddlewareItem19(BaseModel):
    class Config:
        extra = Extra.forbid

    replacePathRegex: Optional[ReplacePathRegexMiddleware] = None


class HttpMiddlewareItem20(BaseModel):
    class Config:
        extra = Extra.forbid

    retry: Optional[RetryMiddleware] = None


class HttpMiddlewareItem21(BaseModel):
    class Config:
        extra = Extra.forbid

    stripPrefix: Optional[StripPrefixMiddleware] = None


class HttpMiddlewareItem22(BaseModel):
    class Config:
        extra = Extra.forbid

    stripPrefixRegex: Optional[StripPrefixRegexMiddleware] = None


class HttpMiddleware(BaseModel):
    __root__: Union[
        HttpMiddlewareItem,
        HttpMiddlewareItem1,
        HttpMiddlewareItem2,
        HttpMiddlewareItem3,
        HttpMiddlewareItem4,
        HttpMiddlewareItem5,
        HttpMiddlewareItem6,
        HttpMiddlewareItem7,
        HttpMiddlewareItem8,
        HttpMiddlewareItem9,
        HttpMiddlewareItem10,
        HttpMiddlewareItem11,
        HttpMiddlewareItem12,
        HttpMiddlewareItem13,
        HttpMiddlewareItem14,
        HttpMiddlewareItem15,
        HttpMiddlewareItem16,
        HttpMiddlewareItem17,
        HttpMiddlewareItem18,
        HttpMiddlewareItem19,
        HttpMiddlewareItem20,
        HttpMiddlewareItem21,
        HttpMiddlewareItem22,
    ]


class Domain1(BaseModel):
    main: Optional[str] = None
    sans: Optional[List[str]] = None


class Tls3(BaseModel):
    passthrough: Optional[bool] = Field(
        False,
        description='A TLS router will terminate the TLS connection by default. However, the passthrough option can be specified to set whether the requests should be forwarded "as is", keeping all data encrypted.',
    )
    options: Optional[str] = Field(
        None,
        description="The options field enables fine-grained control of the TLS parameters. It refers to a TLS Options and will be applied only if a Host rule is defined.",
    )
    certResolver: Optional[str] = Field(
        None,
        description="If certResolver is defined, Traefik will try to generate certificates based on routers Host & HostSNI rules.",
    )
    domains: Optional[List[Domain1]] = Field(
        None,
        description="You can set SANs (alternative domains) for each main domain. Every domain must have A/AAAA records pointing to Traefik. Each domain & SAN will lead to a certificate request.",
    )


class TcpRouter(BaseModel):
    entryPoints: Optional[List[str]] = Field(
        None,
        description="If not specified, TCP routers will accept requests from all defined entry points. If you want to limit the router scope to a set of entry points, set the entry points option.",
    )
    rule: str = Field(
        ...,
        description="It is important to note that the Server Name Indication is an extension of the TLS protocol. Hence, only TLS routers will be able to specify a domain name with that rule. However, non-TLS routers will have to explicitly use that rule with * (every domain) to state that every non-TLS request will be handled by the router.",
    )
    service: str = Field(
        ...,
        description="You must attach a TCP service per TCP router. Services are the target for the router. TCP routers can only target TCP services (not HTTP services).",
    )
    tls: Optional[Tls3] = Field(
        None,
        description="When a TLS section is specified, it instructs Traefik that the current router is dedicated to TLS requests only (and that the router should ignore non-TLS requests).\n\nBy default, a router with a TLS section will terminate the TLS connections, meaning that it will send decrypted data to the services.",
    )


class Server1(BaseModel):
    address: str = Field(
        ..., description="The address option (IP:Port) point to a specific instance."
    )


class TcpLoadBalancerService(BaseModel):
    servers: List[Server1] = Field(
        ...,
        description="Servers declare a single instance of your program.",
        min_items=1,
    )
    terminationDelay: Optional[float] = Field(
        100,
        description="As a proxy between a client and a server, it can happen that either side (e.g. client side) decides to terminate its writing capability on the connection (i.e. issuance of a FIN packet). The proxy needs to propagate that intent to the other side, and so when that happens, it also does the same on its connection with the other side (e.g. backend side).\n\nHowever, if for some reason (bad implementation, or malicious intent) the other side does not eventually do the same as well, the connection would stay half-open, which would lock resources for however long.\n\nTo that end, as soon as the proxy enters this termination sequence, it sets a deadline on fully terminating the connections on both sides.\n\nThe termination delay controls that deadline. It is a duration in milliseconds, defaulting to 100. A negative value means an infinite deadline (i.e. the connection is never fully terminated by the proxy itself).",
    )


class Services(BaseModel):
    name: str
    weight: float


class Weighted(BaseModel):
    services: Services


class TcpWeightedService(BaseModel):
    weighted: Optional[Weighted] = None


class TcpServiceItem(BaseModel):
    class Config:
        extra = Extra.forbid

    loadBalancer: Optional[TcpLoadBalancerService] = None


class TcpServiceItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    weighted: Optional[TcpWeightedService] = None


class TcpService(BaseModel):
    __root__: Union[TcpServiceItem, TcpServiceItem1]


class UdpRouter(BaseModel):
    entryPoints: Optional[List[str]] = Field(
        None,
        description="If not specified, UDP routers will accept packets from all defined (UDP) entry points. If one wants to limit the router scope to a set of entry points, one should set the entry points option.",
    )
    service: str = Field(
        ...,
        description="There must be one (and only one) UDP service referenced per UDP router. Services are the target for the router.",
    )


class Server2(BaseModel):
    address: str


class UdpLoadBalancerService(BaseModel):
    servers: List[Server2] = Field(
        ...,
        description="The servers field defines all the servers that are part of this load-balancing group, i.e. each address (IP:Port) on which an instance of the service's program is deployed.",
        min_items=1,
    )


class Services1(BaseModel):
    name: str
    weight: float


class Weighted1(BaseModel):
    services: Services1


class UdpWeightedService(BaseModel):
    weighted: Optional[Weighted1] = None


class UdpServiceItem(BaseModel):
    class Config:
        extra = Extra.forbid

    loadBalancer: Optional[UdpLoadBalancerService] = None


class UdpServiceItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    weighted: Optional[UdpWeightedService] = None


class UdpService(BaseModel):
    __root__: Union[UdpServiceItem, UdpServiceItem1]


class Http(BaseModel):
    routers: Optional[Dict[str, HttpRouter]] = None
    services: Optional[Dict[str, HttpService]] = None
    middlewares: Optional[Dict[str, HttpMiddleware]] = Field(
        None,
        description="Attached to the routers, pieces of middleware are a means of tweaking the requests before they are sent to your service (or before the answer from the services are sent to the clients).\n\nThere are several available middleware in Traefik, some can modify the request, the headers, some are in charge of redirections, some add authentication, and so on.\n\nPieces of middleware can be combined in chains to fit every scenario.",
    )


class Tcp(BaseModel):
    routers: Optional[Dict[str, TcpRouter]] = None
    services: Optional[Dict[str, TcpService]] = Field(
        None,
        description="Each of the fields of the service section represents a kind of service. Which means, that for each specified service, one of the fields, and only one, has to be enabled to define what kind of service is created. Currently, the two available kinds are LoadBalancer, and Weighted.",
    )


class Udp(BaseModel):
    routers: Optional[Dict[str, UdpRouter]] = Field(
        None,
        description='Similarly to TCP, as UDP is the transport layer, there is no concept of a request, so there is no notion of an URL path prefix to match an incoming UDP packet with. Furthermore, as there is no good TLS support at the moment for multiple hosts, there is no Host SNI notion to match against either. Therefore, there is no criterion that could be used as a rule to match incoming packets in order to route them. So UDP "routers" at this time are pretty much only load-balancers in one form or another.',
    )
    services: Optional[Dict[str, UdpService]] = Field(
        None,
        description="Each of the fields of the service section represents a kind of service. Which means, that for each specified service, one of the fields, and only one, has to be enabled to define what kind of service is created. Currently, the two available kinds are LoadBalancer, and Weighted.",
    )


class Model(BaseModel):
    http: Optional[Http] = None
    tcp: Optional[Tcp] = None
    udp: Optional[Udp] = None
    tls: Optional[Tls] = Field(
        None,
        description="Configures the TLS connection, TLS options, and certificate stores.",
    )
