networks:
  portal:
    name: portal

services:

  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    #environment:
      #- AZURE_CLIENT_ID=todo
      #- AZURE_CLIENT_SECRET=todo
      #- AZURE_SUBSCRIPTION_ID=todo
      #- AZURE_TENANT_ID=todo
      #- AZURE_RESOURCE_GROUP=todo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dyn/:/traefik_dyn/
      - ./acme.json:/acme.json
    networks:
      - portal
    depends_on:
      - shard_core

  shard_core:
    image: ghcr.io/freeshardbase/freeshard:0.32.0
    container_name: shard_core
    restart: always
    volumes:
      - .:/core
      - ./user_data:/user_data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portal
    environment:
      - GCONF_DNS_ZONE=localhost
      - GCONF_TRAEFIK_ACME_EMAIL=user@example.com # todo: change this

  web-terminal:
    image: ghcr.io/freeshardbase/web-terminal:0.36.0
    container_name: web-terminal
    restart: always
    networks:
      - portal