name: Snapshot
run-name: Snapshot ${{ github.ref_name }}

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      full: ${{ github.event_name == 'pull_request' }}

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
    steps:
      - name: Inject enhanced GitHub environment variables
        uses: rlespinasse/github-slug-action@v5
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/freeshardbase/freeshard:${{ env.GITHUB_REF_NAME_SLUG }}
