name: Lint and Test

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Set up just
        uses: extractions/setup-just@v2
      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install ".[dev]"
      - name: Run verify
        run: just verify
