name: Lint and Test

on:
  workflow_call:
    inputs:
      sparse:
        types: [boolean]
        default: false

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install ".[dev]"
      - name: Run Ruff
        run: |
          source venv/bin/activate
          ruff check .

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install ".[dev]"
      - name: Run Pytest
        env:
          CONFIG: tests/config.yml
          TEST_ENV: ${{ github.event.inputs.sparse && 'sparse' ||'full' }}
        run: |
          source venv/bin/activate
          pytest tests
